// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEofuM3ipUevxy6tvHrg7DQGKq2hFfvSk',
    appId: '1:846442944548:web:0577d6e2f933ba11b620b1',
    messagingSenderId: '846442944548',
    projectId: 'ambulance1-app-a5d92',
    authDomain: 'ambulance1-app-a5d92.firebaseapp.com',
    storageBucket: 'ambulance1-app-a5d92.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5zUve8O-WcRLnaRKJs1ZfCGRCSCiIoB0',
    appId: '1:846442944548:android:c0b984c7ecd8eb47b620b1',
    messagingSenderId: '846442944548',
    projectId: 'ambulance1-app-a5d92',
    storageBucket: 'ambulance1-app-a5d92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4HdILLgY6V3Hk6zHXkY_r4d6jPm3s2kU',
    appId: '1:846442944548:ios:b543fed3ebea7e71b620b1',
    messagingSenderId: '846442944548',
    projectId: 'ambulance1-app-a5d92',
    storageBucket: 'ambulance1-app-a5d92.firebasestorage.app',
    iosBundleId: 'com.example.apps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4HdILLgY6V3Hk6zHXkY_r4d6jPm3s2kU',
    appId: '1:846442944548:ios:b543fed3ebea7e71b620b1',
    messagingSenderId: '846442944548',
    projectId: 'ambulance1-app-a5d92',
    storageBucket: 'ambulance1-app-a5d92.firebasestorage.app',
    iosBundleId: 'com.example.apps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEofuM3ipUevxy6tvHrg7DQGKq2hFfvSk',
    appId: '1:846442944548:web:fe738b3d84de28adb620b1',
    messagingSenderId: '846442944548',
    projectId: 'ambulance1-app-a5d92',
    authDomain: 'ambulance1-app-a5d92.firebaseapp.com',
    storageBucket: 'ambulance1-app-a5d92.firebasestorage.app',
  );
}
